version : '3.10.11'

services:
  project:
    depends_on:
      - database
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py pull && python manage.py runserver 0:8000"
    container_name: django
    volumes:
      - .:/home/project
    ports:
      - "8000:8000"
    restart: always
    
  database:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: 'crud_db'
      MYSQL_ROOT_PASSWORD: 'abc@12345'
    ports:
      - "3306:3306"
  

